backend:
  name: git-gateway
  branch: main

collections:
  - name: test
    label: Test
    folder: content/test
    create: true
    fields:
      - {label: Title, name: title, widget: string}
      - {label: Body, name: body, widget: markdown}